### ISSUE TITLE
[Enhancement]Applied Energistics Cabble(s)

### ISSUE THREAD

**Issue by CubeWrench202** [MrTJP/ForgeRelocationFMP#1]
You cannot place Applied energistics inside a Frame block or place a cable and then a Frame in it.

**Comment by retep998** [comment]
I managed to place cables inside frame blocks just fine.

**Comment by CubeWrench202** [comment]
Help me then.

**Comment by CubeWrench202** [comment]
I'll close it, and thanks retep for the info
